customhost = "employee.c25g0ievu2nk.us-east-1.rds.amazonaws.com"
customuser = "aws_user"
custompass = "Bait3273"
customdb = "employee"
custombucket = "assignment-employee"
customregion = "us-east-1a"
